### ISSUE TITLE
Something wrong？

### ISSUE THREAD

**Issue by Wongcheukwai** [darkefyre/sepsisrl#1]
Excuse me. Is there something wrong with the code? May I ask why you deleted some folder?

**Comment by aniruddhraghu** [comment]
Hi,

This code was meant to be moved to a different repository as it isn't on
the original paper, hence why I moved it. I'll upload it to a new place
once it's more complete.

Thanks,
Aniruddh

**Comment by SakiHimeJ** [comment]
Hi，
Excuse me, May I ask where is the new repository? I want to learn the basic RL algorithm on MIMIC3,thanks

**Comment by paulrich1234** [comment]
@SakiHimeJ @Wongcheukwai have you guys solve the code problems , i am doing something like rf to some researches .if so,could you tell me how to solve this problems Thank you

**Comment by paulrich1234** [comment]
@aniruddhraghu

**Comment by aniruddhraghu** [comment]
This repository has the code that was used in the original paper, for building Deep Q Learning models on the sepsis cohort. 
For more up-to-date data preprocessing code, https://github.com/matthieukomorowski/AI_Clinician is a good resource, and can be used to extract  the sepsis cohort. It also contains code for learning policies with value iteration on the discretised state space.
