### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by utomocp** [darkefyre/sepsisrl#2]
Hi, 

Could you please share your dataset used in your codes (rl_train_data_final_discrete.csv and others)?

Thanks.

**Comment by aniruddhraghu** [comment]
Hi,

The dataset used (MKDataset) is extracted from MIMIC-III using code here:
https://github.com/matthieukomorowski/ICURL.

I can't upload the dataset online due to data use agreements for medical
data, but you can request access here:
https://mimic.physionet.org/gettingstarted/access/

**Comment by utomocp** [comment]
Hi, 

Thank you for your guides. I'll try to extract the data from there.

**Comment by JACKHAHA363** [comment]
The page https://github.com/matthieukomorowski/ICURL is not found anymore?

**Comment by sgfin** [comment]
@JACKHAHA363  Looks like a forked version can be found here: https://github.com/AjayTalati/ICURL

**Comment by SamG97** [comment]
Hi,

I was wondering if you could explain how to go about using the code in the ICURL repo to create the MKdataset07Feb17.csv file used in the code here from the MIMIC-III database (which I have access to). The two relevant looking files seem to be in the MIMIC directories but they are just some SQL queries that seem to be missing some of the features present in the MKdataset07Feb17.csv file (e.g. max_dose_vaso) and that they wouldn't make a single file.

Thanks for any help.

**Comment by CongDo0820** [comment]
> Hi,
> 
> I was wondering if you could explain how to go about using the code in the ICURL repo to create the MKdataset07Feb17.csv file used in the code here from the MIMIC-III database (which I have access to). The two relevant looking files seem to be in the MIMIC directories but they are just some SQL queries that seem to be missing some of the features present in the MKdataset07Feb17.csv file (e.g. max_dose_vaso) and that they wouldn't make a single file.
> 
> Thanks for any help.

Hi Sam,
Have you had the answer to your problem? I've got the same trouble. How can I store all the query results into the single csv file like the MKdataset07Feb17.csv file?
Thanks for any help.
