### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by siddharthnishtala** [darkefyre/sepsisrl#5]
Hi,

Thank you for making the code available. I was wondering if it would be possible to upload the 'capping_values.csv' file that was used during the preprocessing of data. Also, is the capping here different from the capping done during the [preprocessing of data in MATLAB](https://github.com/matthieukomorowski/AI_Clinician/blob/master/AIClinician_mimic3_dataset_160219.m)?

Thank you,
Siddharth

**Comment by aniruddhraghu** [comment]
The capping done in MATLAB should be similar to what was done in my code. That version of the data preprocessing is a more up-to-date version (including capping), so I would defer to what is being done there.

**Comment by siddharthnishtala** [comment]
Thank you so much for your prompt reply. Really appreciate it!

**Comment by CongDo0820** [comment]
> Hi,
> 
> Thank you for making the code available. I was wondering if it would be possible to upload the 'capping_values.csv' file that was used during the preprocessing of data. Also, is the capping here different from the capping done during the [preprocessing of data in MATLAB](https://github.com/matthieukomorowski/AI_Clinician/blob/master/AIClinician_mimic3_dataset_160219.m)?
> 
> Thank you,
> Siddharth

Hi,
Can you explain a little bit more about how to get the 'capping_values.csv' file? I've run the Matlab code and just saw it generated the final dataset. 
Thank you!
