### ISSUE TITLE
Problem going from data extracted by AI_Clinician/ICURL to MKdataset.csv

### ISSUE THREAD

**Issue by ardywibowo** [darkefyre/sepsisrl#6]
Hello,
This is very interesting work you have done. I am trying to recreate the results you had, but I seem to be stuck in the data extraction/preprocessing step. I have set up the MIMIC database locally and had already ran the data_extraction code from the ICURL/AI_Clinician repository. However, I am still confused on how to go from the multiple .csv files derived from these codes to the MKDataset.csv file you had in the preprocessing folder.

Any help would be appreciated.

Best,
Randy

**Comment by CongDo0820** [comment]
Hi,
You should run the matlab code to recreate the database from the ICURL/AI_Clinician repository.

**Comment by ardywibowo** [comment]
I see. For anyone confused, you need to run the sepsis3 matlab code then the mimic3 code from AIClinician, and don't erase variables between the two code runs.

Also, there is a difference between the matlab code derived data and the MKDataset.csv, It seems that the intervention fields were renamed from input_total and input_4hourly to input_total_tev and input_4hourly_tev.
