### ISSUE TITLE
data

### ISSUE THREAD

**Issue by Muhammet-Karadeniz** [darkefyre/sepsisrl#7]
Hello. I am a researcher who does not have much experience in reinforcement learning. Could you send me the dataset of your "Continuous State-Space Models for Optimal Sepsis Treatment - a Deep Reinforcement Learning Approach" study? Thanks.

**Comment by aniruddhraghu** [comment]
Hi, sorry for the delay in getting back. The dataset for the experiments is unfortunately not publicly available, but you can generate an updated version of the cohort by following the instructions at this repository: https://github.com/matthieukomorowski/AI_Clinician. This repository also has good instructions on producing the dataset: https://github.com/clinicalml/trajectory-inspection
